### ISSUE TITLE
Direct person to person chat

### ISSUE THREAD

**Issue by dimitri320** [sdey0081/ionic-messenger-starter#2]
Is Direct person to person chat available? I've downloaded the code, but could see the functionality available. Maybe it's somewhere else? Thanks!

**Comment by sdey0081** [comment]
A little busy with other projects, but if I have a chance, I will push it soon.

**Comment by dimitri320** [comment]
@sdey0081 thanks! I've already done it myself, it was rather simple. The difficult thing is the Scroll and input text area with the opening Keyboard. Now you have Scroll disabled (which is good), but the input text area gets hidden behind the Keyboard. Any ideas how to fix it, so it works like in WhatsApp?
