### ISSUE TITLE
Updating to AngularFire 5.0

### ISSUE THREAD

**Issue by majuril** [sdey0081/ionic-messenger-starter#4]
Hi,
really nice app-starter! Any plans to update it to support AngularFire 5.0? I'll try to look into it myself and see if there is anything I can do.

**Comment by sdey0081** [comment]
Good question, but I am so busy with other projects now. You can easily upgrade it to angularfire2 v5.0 following this [guide](https://github.com/angular/angularfire2/blob/master/docs/version-5-upgrade.md#50). Thanks.

**Comment by majuril** [comment]
I've now forked the project to support ionic 4.x, angular 4.4.x, angularfire5 (https://github.com/majuril/ionic-messenger-starter). Everything else is working expect the getFullProfile()-function in auth.ts. I'm unable to link the user profiles from each user to chat messages, Profile-page work as desired.

If you have time and you are familiar with angularfire5 feel free to check it out. Thanks!

**Comment by xdrone2008** [comment]
Hi @majuril , this issue is fixed [here](https://github.com/sdey0081/ionic-messenger-starter/pull/7). Regards.
