### ISSUE TITLE
There is a visible problem!

### ISSUE THREAD

**Issue by orhanbhr** [sdey0081/ionic-messenger-starter#5]
Hello there,

This seems to be a problem for the demo, this task has been opened for you to learn.

Screenshot : http://prntscr.com/h42hrp

**Comment by xdrone2008** [comment]
Hey, it is a bug of ionic old version, https://github.com/ionic-team/ionic/issues/11454. And i think it fixed it already on the latest one. But i didn't update it yet. :)

**Comment by xdrone2008** [comment]
Since @sdey0081 is so busy, i will assist him for a while. {!}

**Comment by orhanbhr** [comment]
You are so fast, I admire your interest. ;) 👍
